<script>
	import { goto } from '$app/navigation';
</script>

<header>
	<h1>MartynasXS toolbox</h1>
	<p>Some silly stuff</p>
</header>

<section>
	<div style="gap: 1rem;">
		<button
			class="card interactable-card"
			on:click={() => {
				goto('/meshfn');
			}}
		>
			<img src="./Images/Program.webp" alt="Model example" width="200" height="200" />
			<div class="container">
				<p>Start Generating</p>
			</div>
		</button>
		<button
			class="card interactable-card"
			on:click={() => {
				goto('/skindb');
			}}
		>
			<img
				src="https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/champion-icons/1.png"
				alt="Model example"
				width="200"
				height="200"
			/>
			<div class="container">
				<p>SkinDB</p>
			</div>
		</button>
	</div>
	<a href="https://github.com/TheMartynasXS/MartynasXS">
		<button class="card interactable-card">
			<div class="container">
				<p>Open github</p>
			</div>
		</button>
	</a>
</section>
<footer class="card">
	<p>Models generated by the website are free to be used in any capacity.</p>
	<p>© 2024 MartynasXS</p>
</footer>

<style>
	header > p {
		text-align: center;
		font-size: 1rem;
		font-weight: 500;
		/* drop shadow */
		text-shadow: 0 0rem 0.5rem var(--shadow);
	}
	header {
		display: grid;
		justify-content: center;
		align-content: center;
		width: 100dvw;
		grid-template-rows: 2.5fr, 1fr;
		padding-inline: 1rem;
		background: rgba(7, 7, 7, 0.25);
		box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
		border: 1px solid rgba(7, 7, 7, 0.45);
	}
	section {
		display: grid;

		place-items: center;
		gap: 1rem;
		margin: 2rem;
	}
	section > div {
		grid-template-columns: repeat(2, 1fr);
		display: grid;
		gap: 1rem;
	}

	h1 {
		color: var(--accent);
		font-size: 3rem;
		font-weight: 800;
		transform: rotate3d(0, 1, 1, 0.02turn);
		text-align: center;
		/* drop shadow */
		text-shadow: 0 0rem 0.5rem var(--shadow);
	}
	.card {
		min-width: 15rem;
		transition: 300ms;
		border-radius: 5px; /* 5px rounded corners */
		padding-inline: 1rem;
		background: rgba(7, 7, 7, 0.25);
		box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
		border: 1px solid rgba(7, 7, 7, 0.45);
		font-size: larger;
	}
	.card.interactable-card:hover {
		transform: scale(1.06);
		cursor: pointer;
		color: var(--accent);
	}
	.card.interactable-card:hover > img {
		transition: all 200ms;
		transform: scale(1.06);
	}
	.card.interactable-card > img {
		transition: all 100ms;
	}
	.card.interactable-card:hover p {
		color: var(--accent);
	}
	.container {
		display: grid;
		place-items: center;
	}
	/* Add rounded corners to the top left and the top right corner of the image */
	img {
		border-radius: 5px 5px 0 0;
	}
	footer {
		position: sticky;
		margin-top: auto;
	}
</style>
